// src/components/File.vue
<template>
	<div class="code flex-1 overflow-auto rounded-md prose-md" v-html="content">
	</div>
</template>

<style scoped>
.code {
	position: absolute;
	left: 17rem;
	right: 1rem;
	top: 5rem;
	bottom: 1rem;
}

.code >>> div {
	height: 100%;
}

::-webkit-scrollbar {
	height: 0.5em;
	width: 0.5em;
}
 
::-webkit-scrollbar-track {
	border-radius: 0 0.375rem 0.375rem 0;
	background-color: #444;
}
 
::-webkit-scrollbar-thumb {
	border-radius: 0.375rem;
	background-color: #777;
}
</style>

<script>
export default {
	props: {
		content: String
	}
}
</script>

// src/components/File.jsx
/** @jsx jsx */
import { jsx, css } from '@emotion/react'
import Highlight from './Highlight'

const style = css`
  position: absolute;
  left: 310px;
  right: 30px;
  top: 80px;
  bottom: 30px;
  overflow: auto;
  border-radius: 5px;
  font-size: 1.125rem;

  pre {
    margin: 0;
    height: 100%;
  }

  code {
    padding: 1.5rem;
    width: calc(100% - 3rem);
    height: calc(100% - 3rem);
  }
`

function File({ code }) {
  return (
    <div css={style}>
      <Highlight>{code}</Highlight>
    </div>
  )
}

export default File
