// src/components/Highlight.jsx
/** @jsx jsx */
import { jsx, css } from '@emotion/react'
import { useState, useEffect } from 'react'
import 'highlight.js/styles/monokai.css'

const style = css`
  font-size: 1.125rem;
  
  code {
    border-radius: 5px;
  }
`

function Highlight({ children }) {
  const [syntax, setSyntax] = useState(null)

  useEffect(() => {
    const worker = new Worker('worker/highlight.js')
    worker.onmessage = (event) => { setSyntax(event.data) }
    worker.postMessage(children)
    return () => worker.terminate()
  }, [children])

  return (
    <pre css={style}>
      <code className="hljs" dangerouslySetInnerHTML={{__html: syntax}}></code>
    </pre>
  )
}

export default Highlight

// src/components/Highlight.vue
<template>
	<pre class="h-full"><code class="h-full">{{ code }}</code></pre>
</template>

<style>
::-webkit-scrollbar {
	height: 0.5em;
	width: 0.5em;
}
 
::-webkit-scrollbar-track {
	border-radius: 0 0.375rem 0.375rem 0;
	background-color: #444;
}
 
::-webkit-scrollbar-thumb {
	border-radius: 0.375rem;
	background-color: #777;
}
</style>

<script>
import hljs from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'

export default {
	props: {
		code: String
	},
	mounted() {
		this.highlight()
	},
	methods: {
		highlight() {
			hljs.highlightAll()
		}
	},
	watch: {
		code: 'highlight'
	}
}
</script>
