// src/TitleBar.jsx
/** @jsx jsx */
import { jsx, css } from '@emotion/react'
import { useSelector } from 'react-redux'
import Icon from './components/Icon'

const style = css`
  position: fixed;
  display: flex;
  width: 100%;
  height: 32px;
`

const drag = css`
  flex: 1;
  -webkit-app-region: drag;
`

const windows = css`
  display: flex;
  background: #ddd;
`

const mac = css`
  color: #ddd;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 3px 0 0 13px;
  width: 52px;
  height: 32px;
`

const button = css`
  outline: none;
  padding: 0 0.75rem;
  background: none;
  border: none;

  &:hover {
    background: #aaa;
  }
`

const exit = css`
  &:hover {
    background: #f00;
  }
`

function TitleBar() {
  const platform = useSelector(state => state.app.platform)

  return (
    <div css={style}>
      { platform === 'darwin' && 
        <div css={mac}>
          <Icon width="12" height="12" name="circle" fill="currentColor" />
          <Icon width="12" height="12" name="circle" fill="currentColor" />
          <Icon width="12" height="12" name="circle" fill="currentColor" />
        </div>
      }
      <div css={drag}></div>
      { platform === 'win32' && 
        <div css={windows}>
          <button css={button} onClick={() => window.electron.send('window/minimize')}>
            <Icon name="minus" width="16" height="16" />
          </button>
          <button css={button} onClick={() => window.electron.send('window/maximize')}>
            <Icon name="square" width="16" height="16" />
          </button>
          <button css={[button, exit]} onClick={() => window.electron.send('window/close')}>
            <Icon name="x" width="16" height="16" />
          </button>
        </div>
      }
    </div>
  )
}

export default TitleBar

// src/components/TitleBar.vue
<template>
	<div class="flex flex-shrink-0 w-full h-8 bg-gray-100 dark:bg-black">
		<div class="w-64 flex-shrink-0 bg-white dark:bg-gray-800" style="-webkit-app-region: drag;"></div>
		<div class="flex-1" style="-webkit-app-region: drag;"></div>
		<div class="flex-shrink-0 flex items-center dark:text-gray-200" v-if="isWindows">
			<button class="w-12 h-8 flex items-center justify-center focus:outline-none hover:bg-gray-200 dark:hover:bg-gray-700" v-on:click="minimize">
				<Icon icon="minus" width="16" height="16" />
			</button>
			<button class="w-12 h-8 flex items-center justify-center focus:outline-none hover:bg-gray-200 dark:hover:bg-gray-700" v-on:click="maximize">
				<Icon icon="square" width="16" height="16" />
			</button>
			<button class="w-12 h-8 flex items-center justify-center focus:outline-none hover:bg-red-500" v-on:click="close">
				<Icon icon="x" width="16" height="16" />
			</button>
		</div>
	</div>
</template>

<script>
import Icon from './Icon.vue'

export default {
	components: {
		Icon
	},
	computed: {
		isWindows() {
			return window.electron.platform === 'win32'
		}
	},
	methods: {
		close() {
			window.electron.close()
		},
		minimize() {
			window.electron.minimize()
		},
		maximize() {
			window.electron.maximize()
		}
	}
}
</script>
